[tools]
rust = "1.93.1"

[tasks.build]
description = "Build Rust app with Bazel"
run = "cargo build"

[tasks.test]
description = "Run Bazel smoke test"
run = "cargo test"

[tasks.run]
description = "Run Rust app with Bazel"
run = "cargo run"
