apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: {{ .Release.Namespace }}
stringData:
  additional-scrape-configs.yaml: |
    - job_name: test-server-raw
      metrics_path: /metrics
      static_configs:
        - targets: [model-server.model-server.svc.cluster.local:80]