{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "model-server.serviceAccountName" . }}
  labels:
    {{- include "model-server.labels" . | nindent 4 }}
# TODO(you): don't automount the token unless the app needs the k8s API.
automountServiceAccountToken: false
{{- end }}
