{
 "title": "Containers ",
 "tags": [
  "ml-ops",
  "starter",
  "TODO"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network RX/TX per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU per container",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id) (rate(container_cpu_usage_seconds_total[1m]))",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Restart count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "changes(container_start_time_seconds[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}