apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: mlops
type: Opaque
stringData:
  POSTGRES_USER: mlops
  POSTGRES_PASSWORD: mlops
  POSTGRES_DB: mlops
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mlops
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: mlops
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.4-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-credentials
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "mlops"]
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
