---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-app-sealed
  namespace: demo
spec:
  encryptedData:
    API_TOKEN: AgC8lg4ObHyYZHqfxcC8vp3F49U73ufsXQnBSqtrWD2GQBnBqeFP5J8PzUcLH4FverpNF2OL/JJ2VKDf9kj6qRx9R/eBwOSP7DPmfWZxMjjZ6sWywCmuVxEQI25XDSVhqMdpJb84iNPMpe/GCKv8qPQTT16LOo7IchftWaI6kl1a65DpxcEItS9tz0vScQcqTtAFFNemFONyFIRxTU8ncIwzoSGzf1iMJHSinoS0z0mj7HDnR/iIDRV1nIyco+1qc6uAnPkI1q7oeWqcVnzZla6fghEi5KUhMXWqZ6WdYLGSKMjbMe4MzscA//cS9/9TuMgmJdCM8aX9QXZsHLAGGwvUYl+XDn4+lmYObFIGs2VCIjSRVvBtraA+L0WjgnfBA85O5dxEszy1Qwf4XXwPe21qwP57a095WCfdWMoyuQpTGbQRjGyyj6VJEoHHZj0XnA4xq82ZlpIbTxKHpDNVlR68Un0l41rN/WdEvOWMBTG3mLn18Tn0YagwT0IoHUT0bbMzEW08fATPyi1p/Z+tm77fb133DUyXGq8+VcwkABFQhOTRyVtlg8UXZ8W+3WXU5hHsyCgj8wtSl9hEA41S29LO64xQGpRfEMvS60EFvS6qGAeFJZXJVByK0yvSkdfC+oucbYmhczDf5kXhQUh1OeZ2uSqpoBpftZbTGrpoSVgUdGRs7OiZUtV597N8Ery+93FeJPr1rlDQ/NjiqWqe5apnURc=
    DB_PASSWORD: AgAoqg2gXM4Qd0Nb7GR2fMT2C4Y4ua/LTHKfZtfyc0g7VjbAp01QE05qgEpmyYVz2KEIv34jEbyc8L3nrFJu85Oj5KdnwV+2RUAMs20WKOal+9TRACKETRq9SCkjUgofuLQcX1NyTi8i4rqAvQHewx00/1aiPPY51oj3uUIZwfrEho6tzFyIfDOZFVZdoo7jdUHiCC4sJQp86VmzRkH8/3kzlpC3EXxGOUGRQgWWPIGmUyoJHPe/kIkDSTGGEolSMIrqEx4lImJUmioL+zE8AOayZGagQrpAHNqbSwVFQiKQv2L9p4sCgqt3uJb+9cDoU6LYBcxC7XH9od0whzqYPIftGP8O+kNLgbYNuAvZajX9vL0CiRyUrIrh4Nr3tdW5ZWAAlK3X1buYn9RoPQNT+0JFwFyR3DfpWZoPufxBX/FRz/DkeJ/1BedLSYQVwSvTVsystQjxPenqZHFGehklAPF+k1ZIgz3SIl//m/MNPmmVPHrA91KGqwPXChHco3wcXOJpBsrTgbpcmR/OqtujzInc8AyWxTWHmK7BnRoqasY7aLIPzAhM2r7Ak4RxODh5x6nbqRBoHS/3Aobcp8qU+6NFMapm7x0+Ohjg4xduZhGQ5+sisjBj9VpE7+5mya37u1DcpmT52d3fewl9yXgJXTqjTA9DRtO5TmVQAKJWXVY4sG1AZcEAeZh/UVY26KUZc2j1UOaZLaRDXPj4Gw==
  template:
    metadata:
      creationTimestamp: null
      name: demo-app-sealed
      namespace: demo
