services:
  redis:
    image: redis:7.4-alpine
    container_name: mlops_redis
    command: ["redis-server", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 2s
      timeout: 3s
      retries: 10
