{
 "title": "Triton Inference",
 "tags": [
  "triton",
  "little-ml-story"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Inference count (per model)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (model) (rate(nv_inference_count[1m]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Avg request duration (us)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (model) (rate(nv_inference_request_duration_us[5m])) / sum by (model) (rate(nv_inference_request_success[5m]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Queue duration (us)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (model) (rate(nv_inference_queue_duration_us[5m])) / sum by (model) (rate(nv_inference_request_success[5m]))",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}