server:
    verbosity: 1
    interface: 0.0.0.0
    access-control: 10.20.0.0/24 allow
    do-ip6: no
    cache-min-ttl: 0
    cache-max-ttl: 60
    log-queries: yes
    log-replies: yes

forward-zone:
    name: "lab.local"
    forward-addr: 10.20.0.10

forward-zone:
    name: "."
    forward-addr: 1.1.1.1
    forward-addr: 8.8.8.8
