version: "3.5"

services:
  lakefs:
    image: treeverse/lakefs:1
    # depends_on:
    #   - minio-setup
    ports:
      - "8000:8000"
    environment:
      - LAKEFS_DATABASE_TYPE=local
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://minio:9000
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=minioadmin
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=minioadmin
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=minioadmin
      - LAKEFS_LOGGING_LEVEL=INFO
      - LAKEFS_STATS_ENABLED=${LAKEFS_STATS_ENABLED:-1}
      - LAKEFS_INSTALLATION_USER_NAME=bob
      - LAKEFS_INSTALLATION_ACCESS_KEY_ID=AKIAIOSFOLKFSSAMPLES
      - LAKEFS_INSTALLATION_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - LAKECTL_CREDENTIALS_ACCESS_KEY_ID=AKIAIOSFOLKFSSAMPLES
      - LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - LAKECTL_SERVER_ENDPOINT_URL=http://localhost:8000
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        lakefs run --local-settings &
        wait-for -t 60 lakefs:8000
        echo ""
        wait-for -t 60 minio:9000 && echo '------------------------------------------------

              MinIO admin:   http://127.0.0.1:9001/
              
                              Username : minioadmin
                              Password : minioadmin
        '
        echo "------------------------------------------------"
        echo ""
        echo "lakeFS Web UI: http://127.0.0.1:8000/      >(.＿.)<"
        echo "                                             (  )_ "
        echo ""
        echo "                Access Key ID    : $$LAKEFS_INSTALLATION_ACCESS_KEY_ID"
        echo "                Secret Access Key: $$LAKEFS_INSTALLATION_SECRET_ACCESS_KEY"
        echo ""
        echo "-------- Let's go and have axolotl fun! --------"
        echo ""
        wait

  # minio-setup:
  #   image: minio/mc:latest
  #   environment:
  #     - MC_HOST_lakefs=http://minioadmin:minioadmin@minio:9000
  #   depends_on:
  #     - minio
  #   volumes:
  #     - /opt/lakefs/data:/data
  #   entrypoint: ["/bin/sh", "-c"]
  #   command:
  #       - |
  #         mc mb lakefs/quickstart lakefs/example lakefs/sample-data

  minio:
    image: minio/minio:latest
    volumes:
      - ${LAKEFS_MINIO_VOLUME:-/opt/lakefs/data}:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: ["minio", "server", "/data", "--console-address", ":9001"]

networks:
  default:
    name: lakefs