services:
  postgres:
    image: postgres:16
    container_name: mlops_postgres
    environment:
      POSTGRES_USER: mlops
      POSTGRES_PASSWORD: mlops
      POSTGRES_DB: registry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlops -d registry"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
