apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-k8s-reader
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-k8s-reader-role
  namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-k8s-reader-role-binding
  namespace: secret-source
subjects:
  - kind: ServiceAccount
    name: eso-k8s-reader
    namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-k8s-reader-role
