{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "records-api.name" . }}
    app.kubernetes.io/part-of: db-lab
    db-lab.example/tier: api
{{- end }}
