[tools]
python = "3.13"

[tasks.compose]
description = "launch docker compose"
run = """
docker compose up -d mlflow ml-app prometheus grafana cadvisor node-exporter blackbox-exporter alertmanager
"""