min_version = "2026.4.0"

[settings]
lockfile = true


[tasks."prepare_env"]
description = "Setups environemnt"
run = """
set -euo pipefail

if ! command -v docker >/dev/null 2>&1; then
    echo "Installing docker"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    echo "Docker installed 🫰"
fi

sudo groupadd -f docker
sudo usermod -aG docker "$USER"
newgrp docker
"""


[tasks."verify_env"]
description = "Verify environemnt"
run = """
if ! command -v docker >/dev/null 2>&1; then
    echo "Docker is not installed ❌"
    exit 1
fi

echo "Everything set up ✅"
"""


[tasks."run"]
description = "Runs app in development environment"
depends = ['verify_env']
usage = """
    arg "<configuration>" help="Docker compose configuration" default="docker-compose.dev.yml"
"""
run = """
docker compose -f {{ usage.configuration }} up --build -d
"""


[tasks."stop"]
description = "Stop docker compose run"
usage = """
    arg "<configuration>" help="Docker compose configuration" default="docker-compose.dev.yml"
"""
run = """
docker compose -f {{ usage.configuration }} down
"""
