name: polywhale-go
on:
  push:
    branches:
      - main
    paths:
      - polywhale/go/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: polywhale-go

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          context: ./polywhale/go
          push: true
          tags: pyretttt/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
